services:
  - type: web
    name: aquelia-backend
    env: node
    plan: free
    buildCommand: npm ci
    startCommand: node backend/server-node.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000 